name: Build Docker Image

on: [push]

vars:
  DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}} 
  DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
  IMAGE_NAME: demo-image-test
  IMAGE_TAG: latest
  IMAGE_FULL_NAME: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}:${{ vars.IMAGE_TAG }}

jobs:
    build:
      name: push docker image to docker hub
      runs-on: ubuntu-latest
      
      steps:
        - uses: actions/checkout@v2
        
        - name: login to docker hub
          id: docker-hub
          env:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ vars.DOCKERHUB_PASSWORD }}
          run: docker login -u $username -p $password 
        
        - name: build the docker image
          id: build-docker-image
          run: |
            ls -la 
            docker build -t ${{ vars.IMAGE_FULL_NAME }} .
        
        - name: push the docker image
          id: push-docker-image
          run: docker push ${{ vars.IMAGE_FULL_NAME }}