name: Build Docker Image

on: [push]

env:
  DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}} 
  DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
  IMAGE_NAME: demo-image-test
  IMAGE_TAG: latest

jobs:
    build:
      name: push docker image to docker hub
      runs-on: ubuntu-latest
      
      steps:
        - uses: actions/checkout@v2
        
        - name: login to docker hub
          id: docker-hub
          run: 
          - docker login -u ${{ env.DOCKERHUB_USERNAME }} -p ${{ env.DOCKERHUB_PASSWORD }}
        
        - name: build the docker image
          id: build-docker-image
          run: |
            IMAGE_FULL_NAME="${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
            docker build -t "$IMAGE_FULL_NAME" .
        
        - name: push the docker image
          id: push-docker-image
          run: |
            IMAGE_FULL_NAME="${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
            docker push "$IMAGE_FULL_NAME"